In [1]:
import numpy as np

In [24]:
np.random.seed(42)

# Input: 1 feature
x1 = np.array([[2.0],
              [1.0]])  # shape (2, 1)

x1

#print(f'x1:\n [x1]'')

array([[2.],
       [1.]])

In [3]:
# Hidden layer: 3 neurons
W1 = np.random.randn(3, 2)   # weights for hidden layer (3x2)
b1 = np.random.randn(3, 1)   # bias for hidden layer (3x1)

print(f'W:\n{W1}\nB:\n{b1}')

W:
[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]
B:
[[ 1.57921282]
 [ 0.76743473]
 [-0.46947439]]


In [5]:
# Output layer: 1 neuron
W2 = np.random.randn(1, 3)   # weights for output layer (1x3)
b2 = np.random.randn(1, 1)   # bias for output layer (1x1)

print(f'W2:\n{W2}\nb2:\n{b2}')

W2:
[[ 0.49671415 -0.1382643   0.64768854]]
b2:
[[1.52302986]]


In [12]:
def relu(z):
    return np.maximum(0 ,z)

def sigmoid(z):
    return 1 / (1 * np.exp(-z))

In [13]:
# Forward pass
# Hidden layer
z1 = np.dot(W1, x1) + b1      # linear
a1 = relu(z1)                # activation
print(f'z1:\n{z1}\na1:\n{a1}')

z1:
[[ 2.43437682]
 [ 3.58584166]
 [-1.17191809]]
a1:
[[2.43437682]
 [3.58584166]
 [0.        ]]


In [14]:
# Output layer
z2 = np.dot(W2, a1) + b2     # linear
a2 = sigmoid(z2)             # activation (e.g., probability of class 1)

print(f'z2:\n{W2}\na2:\n{b2}')

z2:
[[ 0.49671415 -0.1382643   0.64768854]]
a2:
[[1.52302986]]


In [16]:
print("Input x:\n", x1)
print("\nHidden layer linear output (z1):\n", z1)
print("\nHidden layer activation (a1, after ReLU):\n", a1)
print("\nOutput layer linear output (z2):\n", z2)
print("\nFinal output (a2, after sigmoid – can be seen as probability):\n", a2)

Input x:
 [[2.]
 [1.]]

Hidden layer linear output (z1):
 [[ 2.43437682]
 [ 3.58584166]
 [-1.17191809]]

Hidden layer activation (a1, after ReLU):
 [[2.43437682]
 [3.58584166]
 [0.        ]]

Output layer linear output (z2):
 [[2.23642539]]

Final output (a2, after sigmoid – can be seen as probability):
 [[9.35981369]]
