
Data -

iris: [sepal length, sepal width, species ]
titanic: [ pclass sibling spouse fare age gender survival ]
tips: [ ]
penguins: [ species island length widths]

Columns = Vectors

In [ ]:
list2 = [3,4,5, 'idrees', 4.5, [3, ['a','b'],5]]

list2[5][1][0]

'a'

In [24]:
vector_x = [3,4,[5,6,7],3]

vector_x[2][1]

6

In [33]:
vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

sum(vector1) # (24)
len(vector1) # number of element (3)
print(vector1)

[10, 4, 10]


In [39]:
import numpy as np

arr = np.array(vector1)
arr

#arr.max() #10
#arr.min() #4
#arr.mean() #8.0
arr.var() # 8.0
#arr.std() # 2.82

np.float64(8.0)

In [42]:
vector1 = [10,4,10]
vector2 = [20,4,10]
vector3 = [30,4,10]

matrix = [vector1, 
          vector2, 
          vector3] # 0 1 2

matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrix

# how to check the dimensions?

 # [2,4,10] as a result
 # 2 as a result

[[10, 4, 10], [20, 4, 10], [30, 4, 10]]

In [44]:
matrix[0:2][1] # row  x  column

[20, 4, 10]

In [58]:
matrix = [[10,4,10], # 0
          [20,4,10], # 1   # 0
          [30,4,10], # 2   # 1
          [40,4,10]] # 3

matrix_arr = np.array(matrix)
matrix_arr

array([[10,  4, 10],
       [20,  4, 10],
       [30,  4, 10],
       [40,  4, 10]])

In [63]:
type(matrix_arr)
#matrix_arr.ndim

#matrix_arr[1][2] #[10]

#  1 2
matrix_arr[1:3][1] # rows 

array([30,  4, 10])

In [ ]:
matrix_arr[1][2]

np.int64(10)

In [67]:
matrix_arr * 2 # scalar multiplication

# scaler operations with arrays

#matrix_arr.ndim #2
matrix_arr.shape # how many rows and columns

# rows  x  columns

(4, 3)

In [68]:
# broadcastinggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg

matrix_arr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110],
       [140, 104, 110]])

In [70]:
a = np.array([[1, 3, 5, 6],
             [2, 8, 7, 9]]
             )
b = np.array([[10], 
              [100]])

a - b
#a * b
#a / b
#a + b

array([[ -9,  -7,  -5,  -4],
       [-98, -92, -93, -91]])

In [71]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [72]:
((variance)**0.5) .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [73]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22,  650.8])

stdx
stdy


r = covariance/(stdx*stdy)
r

array([0.58575649, 1.70715621])

In [1]:
vector1 = [3,4,10]
vector2 = [2,4,10]

matrix2 = [vector1, vector2]

In [3]:
matrix2

[[3, 4, 10], [2, 4, 10]]

In [5]:
matrix2[1]

[2, 4, 10]

In [6]:
matrix2[1][0]

2

In [75]:
import numpy as np

x = np.array([[1,4,1],
              [2,5,2]])

w = np.array([10,10,10])

w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

mat_multiply_xw = np.dot(x,w)
mat_multiply_xw

array([60, 90])

In [74]:
matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [76]:
matmultiply_xw2 = x @ w2
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [77]:
matmultiply_xw2 = np.matmul(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [20]:
import numpy as np

# Define a scalar
scalar = 3

# Define a NumPy array (vector)
vector = np.array([1, 2, 3, 4])

# Perform scalar multiplication on the vector
result_vector = scalar * vector
print("Result of scalar multiplication on vector:\n", result_vector)

# Define a NumPy array (matrix)
matrix = np.array([[1, 2],
                   [3, 4]])

# Perform scalar multiplication on the matrix
result_matrix = scalar * matrix
print("\nResult of scalar multiplication on matrix:\n", result_matrix)

Result of scalar multiplication on vector:
 [ 3  6  9 12]

Result of scalar multiplication on matrix:
 [[ 3  6]
 [ 9 12]]


In [21]:
import pandas as pd

df = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]}, index=['A', 'B', 'C'])
print(df['A':'B']) # Slices rows with labels 'A' and 'B'

   col1  col2
A     1     4
B     2     5


In [22]:
import pandas as pd

df = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]}, index=['A', 'B', 'C'])

# Slicing rows by label
print(df.loc['A':'C'])

# Slicing rows and columns by label
print(df.loc['A':'B', 'col1':'col2'])

   col1  col2
A     1     4
B     2     5
C     3     6
   col1  col2
A     1     4
B     2     5


In [ ]:
#matrix multiplication

import numpy as np

a = np.array([[2,3,4],
              [6,7,8],
              [3,2,3]])

b = np.array([[5,5,5],
              [2,2,2]])

b @ a

array([[55, 60, 75],
       [22, 24, 30]])