In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
python_list = [1,2,3,"string",6.7]

num_list = [x for x in range(10)]
print(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
print(num_list*3)
print(type(num_list))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [ ]:
#num_list.insert(0,'hello')
num_list.remove('hello')
num_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#num_list.insert(0,'list')
my_list = num_list.index('list')
my_list

0

In [16]:
count_list = num_list.count('list')
count_list

1

In [ ]:
#num_list.remove('list')
#num_list.reverse()
num_list.sort()
num_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [19]:
copy_list = num_list.copy()
copy_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
ary1 = np.array([1,2,3,4,5])
print(ary1)
type(ary1)

[1 2 3 4 5]


numpy.ndarray

In [21]:
print(ary1*3)
print(type(ary1))

[ 3  6  9 12 15]
<class 'numpy.ndarray'>


In [22]:
arr1d = np.array([1,2,3,4])
print(arr1d)
print(arr1d.ndim)

[1 2 3 4]
1


In [23]:
arr2d = np.array([
                [1,2,3],
                [4,5,6]
                ])
print(arr2d)
print(arr2d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [24]:
arr3d = np.array([
        [[1,2,3],[4,5,6]],
        [[7,8,9],[10,11,12]]
        ])

print(arr3d)
print(arr3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [25]:
#Elements in a 3D array are accessed using three indices: 
# [depth, row, column].

element = arr3d[0,1,0]

print(f"Element at [1, 1, 0]: {element}")

Element at [1, 1, 0]: 4


In [26]:
print(f"dimension: {np.ndim(arr1d)}")
print(f"shape: {arr1d.shape}")

print(f"dimension: {np.ndim(arr2d)}")
print(f"shape: {arr2d.shape}")

print("dimension: ",np.ndim(arr3d))
print("shape: ",arr3d.shape)

arr1d.dtype

dimension: 1
shape: (4,)
dimension: 2
shape: (2, 3)
dimension:  3
shape:  (2, 2, 3)


dtype('int64')

In [42]:
shape1d = arr1d.ndim
print(shape1d)

size1d = arr1d.size
print(size1d)

shape2d = arr2d.shape
print(shape2d)

size2d = arr2d.size
print(size2d)

size3d = arr3d.size
size3d

1
4
(2, 3)
6


12

In [43]:
print(arr1d)

[1 2 3 4]


In [ ]:
# broadcasting

arr1d * 30

array([ 30,  60,  90, 120])

In [50]:
arr1d + arr1d

array([2, 4, 6, 8])

In [57]:
arr1 = np.array([1,2,3,])
print(arr1)

arr2 = np.array([[10,20,30],
                [10,20,30]])
print(arr2)

print('Result:',arr1 + arr2)

[1 2 3]
[[10 20 30]
 [10 20 30]]
Result: [[11 22 33]
 [11 22 33]]


In [58]:
a = 10
b = 3
print(a + b) # Addition: 13
print(a - b) # Subtraction: 7
print(a * b) # Multiplication: 30
print(a / b) # Division: 3.333
print(a // b) # Floor Division: 3
print(a % b) # Modulus: 1
print(a ** b) # Exponentiation: 1000

13
7
30
3.3333333333333335
3
1
1000


In [60]:
3**30

205891132094649

In [63]:
prices = np.array([4000000,3500000,2500000])
print(f'The prices are: {prices/1000000} million') # scale data

The prices are: [4.  3.5 2.5] million


In [64]:
import numpy as np

# Create an array from 0 to 4 (stop=5, start=0, step=1 by default)
arr1 = np.arange(5)
print(f"Example 1: {arr1}")

# Create an array from 1 to 9 with a step of 2
arr2 = np.arange(1, 10, 2)
print(f"Example 2: {arr2}")

# Create an array with floating-point numbers
arr3 = np.arange(0.5, 2.5, 0.5)
print(f"Example 3: {arr3}")

# Create a descending array using a negative step
arr4 = np.arange(10, 0, -2)
print(f"Example 4: {arr4}")

Example 1: [0 1 2 3 4]
Example 2: [1 3 5 7 9]
Example 3: [0.5 1.  1.5 2. ]
Example 4: [10  8  6  4  2]


In [78]:
range_numbers = np.arange(1,11)
range_numbers
range_numbers.reshape(5,2) #(column,row)
#print(range_numbers)

# exactly same as this
range_example = np.arange(1,11).reshape(5,2)
print(range_example)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
a = [i for i in range(1000)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [103]:
# only list comprehension we have used
nums = [x for x in range(0,101,2)] 
print(nums)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [113]:
nums1 = nums[100:0:-1] # accessing elements in list
print(nums1)

array_nums = np.array(nums) 
print(array_nums)

print(array_nums[:])

[100, 98, 96, 94, 92, 90, 88, 86, 84, 82, 80, 78, 76, 74, 72, 70, 68, 66, 64, 62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [126]:
line = np.linspace(0,1,10) # values are evenly spaced and stored in array
print(line)

array2 = np.linspace(1, 5, num=3, endpoint=False)
print(array2)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.         2.33333333 3.66666667]


In [172]:
np.zeros((3,3))
np.ones((3,3))
# take in tuples of shape, and return arrays


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [171]:
arr_1d = np.zeros(5)
print(f"1D array: {arr_1d}")

arr_2d = np.zeros((2, 3))
print(f"2D array: {arr_2d}")

arr_3d_int = np.zeros((2, 2, 2), dtype=int)
print(f"3D integer array: {arr_3d_int}")

1D array: [0. 0. 0. 0. 0.]
2D array: [[0. 0. 0.]
 [0. 0. 0.]]
3D integer array: [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [183]:
# random class in numpy 
# numbers

np.random.seed(40)

#random_array = np.random.rand(3,4)
#random_array

random_array = np.random.randint(0,100,(6,2)) # start, stop, (shape)
random_array

array([[70, 91],
       [ 7, 37],
       [56, 50],
       [65, 12],
       [71, 19],
       [31, 74]])

In [190]:
flat_array = random_array.flatten()
flat_array

reshape_array = flat_array.reshape(6,2)
reshape_array


array([[70, 91],
       [ 7, 37],
       [56, 50],
       [65, 12],
       [71, 19],
       [31, 74]])

In [189]:
# transform
reshape_array.T

array([[70,  7, 56, 65, 71, 31],
       [91, 37, 50, 12, 19, 74]])

In [ ]:
# aggregations 

data = np.array([85,94,22,68,94,54,98]) # marks

# sum
# mean
# min max

print(data.sum())

# create a list of 1 to 10
# use list comprehension
# give me the addition of numbers from 1 to 10


515


In [200]:
list1 = [i for i in range(1,11)]

data2 = np.array([(list1)])
print(data2.sum())
data2.mean()

55


np.float64(5.5)

In [199]:
array_idrees = np.array([num for num in range(1,11)])
sum_of_array_idrees = array_idrees.sum()
print(sum_of_array_idrees)
array_idrees.mean()

# list comprehension - [ number : expression ]

55


np.float64(5.5)

In [201]:
a_2d_matrix = np.ones((3,5))

print(a_2d_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [203]:
a_2d_matrix.sum(axis=0) # column wise sum

#a_2d_matrix.sum(axis=1) # row wise sum

array([3., 3., 3., 3., 3.])

In [ ]:
# splitting numpy arrays
# exactly same as this
dataset_array = np.arange(1,101).reshape(50,2) #reshape(row,column)
#print(dataset_array)

# x input ----->  y output
# 1 ------> 2
# rows are 50

train_dataset = dataset_array[:25] # 70 rows [start:stop] [0 (start):25]

test_dataset = dataset_array[25:] # All the rows [25:50 (end)]

print(test_dataset)


[[ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
